/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author diedr
 */
public class JInternalFrame_panel_de_inicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrame_panel_de_inicio
     */
    public JInternalFrame_panel_de_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_laboratorio_panel_ini = new javax.swing.JButton();
        jButton_compra_panel_ini = new javax.swing.JButton();
        jButton_producto_panel_ini = new javax.swing.JButton();
        jButton_venta_panel_ini = new javax.swing.JButton();
        jButton_empleado_panel_ini = new javax.swing.JButton();
        jButton_cliente_panel_ini = new javax.swing.JButton();
        jButton_receta_medica_panel_ini = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jButton_laboratorio_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_laboratorio_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_laboratorio_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Laboratorio panel.png"))); // NOI18N
        jButton_laboratorio_panel_ini.setText("Laboratorio");
        jButton_laboratorio_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_laboratorio_panel_iniActionPerformed(evt);
            }
        });

        jButton_compra_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_compra_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_compra_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/compra panel.png"))); // NOI18N
        jButton_compra_panel_ini.setText("Compra");
        jButton_compra_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_compra_panel_iniActionPerformed(evt);
            }
        });

        jButton_producto_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_producto_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_producto_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Producto panel.png"))); // NOI18N
        jButton_producto_panel_ini.setText("Producto");
        jButton_producto_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_producto_panel_iniActionPerformed(evt);
            }
        });

        jButton_venta_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_venta_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_venta_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/venta panel.png"))); // NOI18N
        jButton_venta_panel_ini.setText("Venta");
        jButton_venta_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_venta_panel_iniActionPerformed(evt);
            }
        });

        jButton_empleado_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_empleado_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_empleado_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/empleado panel.png"))); // NOI18N
        jButton_empleado_panel_ini.setText("Empleado");
        jButton_empleado_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_empleado_panel_iniActionPerformed(evt);
            }
        });

        jButton_cliente_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_cliente_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_cliente_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/clientes panel.png"))); // NOI18N
        jButton_cliente_panel_ini.setText("Cliente");
        jButton_cliente_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cliente_panel_iniActionPerformed(evt);
            }
        });

        jButton_receta_medica_panel_ini.setBackground(new java.awt.Color(204, 204, 255));
        jButton_receta_medica_panel_ini.setForeground(new java.awt.Color(0, 0, 0));
        jButton_receta_medica_panel_ini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/recetas medica panel.png"))); // NOI18N
        jButton_receta_medica_panel_ini.setText("Receta médica");
        jButton_receta_medica_panel_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_receta_medica_panel_iniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_venta_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_laboratorio_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_empleado_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_compra_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_producto_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jButton_cliente_panel_ini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_receta_medica_panel_ini)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_laboratorio_panel_ini)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_venta_panel_ini)
                            .addComponent(jButton_empleado_panel_ini)
                            .addComponent(jButton_cliente_panel_ini)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_producto_panel_ini)
                        .addComponent(jButton_compra_panel_ini)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton_receta_medica_panel_ini)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_producto_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_producto_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_producto_panel_iniActionPerformed

    private void jButton_laboratorio_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_laboratorio_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_laboratorio_panel_iniActionPerformed

    private void jButton_compra_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_compra_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_compra_panel_iniActionPerformed

    private void jButton_venta_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_venta_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_venta_panel_iniActionPerformed

    private void jButton_empleado_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_empleado_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_empleado_panel_iniActionPerformed

    private void jButton_cliente_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cliente_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cliente_panel_iniActionPerformed

    private void jButton_receta_medica_panel_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_receta_medica_panel_iniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_receta_medica_panel_iniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cliente_panel_ini;
    private javax.swing.JButton jButton_compra_panel_ini;
    private javax.swing.JButton jButton_empleado_panel_ini;
    private javax.swing.JButton jButton_laboratorio_panel_ini;
    private javax.swing.JButton jButton_producto_panel_ini;
    private javax.swing.JButton jButton_receta_medica_panel_ini;
    private javax.swing.JButton jButton_venta_panel_ini;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
